import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "{{name}}",
  description: "Generated by appncy",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="container m-auto grid min-h-screen grid-rows-[auto,1fr,auto] px-4 bg-background font-sans antialiased dark">
        <header className="text-xl font-bold leading-10">{{name}}</header>
        <main className="py-8">{children}</main>
        <footer className="text-center leading-10 opacity-70">
          © {new Date().getFullYear()} {{name}}
        </footer>
      </body>
    </html>
  );
}
